### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by sberryman** [alexattia/ExtendedTinyFaces#1]
Thanks for posting the paper and the code, stumbled upon this during my routine arxiv reading! Do you have any plans to release the pre-trained model?

Edit: Apparently I should have read through the code a bit more. It looks like you are using the pre-trained model from [Tiny_Faces_in_Tensorflow](https://github.com/cydonia999/Tiny_Faces_in_Tensorflow)

**Comment by alexattia** [comment]
Exactly! We are using pre-trained model from [Tiny Faces in TensorFlow](https://github.com/cydonia999/Tiny_Faces_in_Tensorflow). You have to download the MATLAB pretrained model and then convert it into pickle. We let for future work to do it with other pretrained model (instead of ResNet-101).

**Comment by sberryman** [comment]
Thanks for exposing me to tiny faces, looking forwarding to running eval/inference on a few of my datasets.
