### ISSUE TITLE
got an unexpected keyword argument 'framee' when calling function tiny.evaluate in Video detection

### ISSUE THREAD

**Issue by ziganlan** [alexattia/ExtendedTinyFaces#5]
Thanks for sharing, but I still have some questions when running Video detection. it got a error when calling function tiny.evaluate:
  TypeError: evaluate() got an unexpected keyword argument 'framee'
where tiny.evaluate(...) is defined in Tiny_Faces_in_Tensorflow/tiny_face_eval/ like follow style:

def evaluate(weight_file_path, data_dir, output_dir, prob_thresh=0.3, nms_thresh=0.1, lw=3, display=False):
No argument 'framee' indeed. So, you modified the original code ? 
I will be even more grateful if you can help me.

**Comment by Elephantameler** [comment]
Maybe you can change to "img"

**Comment by ziganlan** [comment]
@Elephantameler  Thanks for answer！My problem is solve by replace “tiny.evaluate(...)" by "evaluate.evaluate(...)", which is modified from  “tiny.evaluate(...)" in Tiny_Faces_in_Tensorflow repository.

**Comment by Elephantameler** [comment]
oh, yes!  I have an another question: Do you know where I can find out '/home/alexattia/Work/RecVis/famvk.avi', this avi file?
